name: Code Coveralls

on:
    pull_request:
      branches:
        - master
jobs:
    build:
        runs-on:  ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Intall Node.js
            uses: actions/setup-nodev@v1
            with:
                node-version: 12.x
            - run: yarn
            - run: yarn test
            env:
                CI: true